# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - step:
        script:
        - echo "lovely build step would be here"
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - mkdir ../wordsearch
          - mv * ../wordsearch
          - mv ../wordsearch .
          - pipe: atlassian/sftp-deploy:0.7.0
            variables:
              USER: 'j1jjujqhggs6'
              SERVER: 'verygoodbadthing.com'
              REMOTE_PATH: '/home/j1jjujqhggs6/public_html'
          
