# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  custom:
    deploy-to-webserver:
      - step:
          deployment: production
          name: 'Tear down previous deployment'
          script:
            - envsubst < ./deployment_teardown_old.sh > deploy_teardown.sh
            - pipe: atlassian/ssh-run:0.6.1
              variables:
                SSH_USER: $REMOTE_USER
                SERVER: $REMOTE_HOST
                MODE: 'script'
                COMMAND: 'deploy_teardown.sh'
      - step:
          name: 'Deploy public_html'
          script:
            - bash ./prepare_public_html.sh
            - pipe: atlassian/sftp-deploy:0.7.0
              variables:
                USER: $REMOTE_USER
                SERVER: $REMOTE_HOST
                REMOTE_PATH: $REMOTE_PUBLIC_HTML_PATH
      - step:
          name: 'Deploy backend'
          script:
            - bash ./prepare_backend.sh
            - pipe: atlassian/sftp-deploy:0.7.0
              variables:
                USER: $REMOTE_USER
                SERVER: $REMOTE_HOST
                REMOTE_PATH: $REMOTE_PATH
      - step:
          name: 'Install word_search_generator'
          script:
            - envsubst < ./deployment_install.sh > deploy_install.sh
            - pipe: atlassian/ssh-run:0.6.1
              variables:
                SSH_USER: $REMOTE_USER
                SERVER: $REMOTE_HOST
                MODE: 'script'
                COMMAND: 'deploy_install.sh'
